name: google_geocoding
description: A new Flutter package for handle google geocoding api that geocoding and reverse geocoding requests are available
version: 0.1.5
homepage: https://github.com/bazrafkan/google_geocoding

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
